export const AUTHENTICATION_SUCCESSFUL = 'AUTHENTICATION_SUCCESSFUL';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SMS_GENERATION_SUCCESSFUL = 'SMS_GENERATION_SUCCESSFUL';
export const SMS_GENERATION_FAILURE = 'SMS_GENERATION_FAILURE';
export const SMS_VERIFICATION_FAILURE = 'SMS_VERIFICATION_FAILURE';
export const SMS_VERIFICATION_SUCCESSFUL = 'SMS_VERIFICATION_SUCCESSFUL';
