export const FETCH_LISTING_SUCCESSFUL = 'FETCH_LISTING_SUCCESSFUL';
export const FETCH_LISTING_FAILED = 'FETCH_LISTING_FAILED';
export const SUBMIT_LISTING_SUCCESSFUL = 'SUBMIT_LISTING_SUCCESSFUL';
export const SUBMIT_LISTING_FAILED = 'SUBMIT_LISTING_FAILED';
