export const SUBMIT_OFFER_SUCCESSFUL = 'SUBMIT_OFFER_SUCCESSFUL';
export const SUBMIT_OFFER_FAILED = 'SUBMIT_OFFER_FAILED';
export const ACCEPT_OFFER_SUCCESSFUL = 'ACCEPT_OFFER_SUCCESSFUL';
export const ACCEPT_OFFER_FAILED = 'ACCEPT_OFFER_FAILED';
